[
    {'kind': 'Listing', 'data': {'after': None, 'dist': 1, 'modhash': '', 'geo_filter': '', 'children': [
                {'kind': 't3', 'data': {'approved_at_utc': None, 'subreddit': 'copypasta', 'selftext': 'A girlfriend of mine was having a good day in the house. but suddenly; she got shrunk. she tried to move but she fell. also, she started to see tiny dots on the floor that she could 
walk on. when she walked on the dots, she couldn\'t move again. She called 911 and 12 invisible cops arrived to her. and they were fluent at Assyrian. and the cops started to pick her up. A paper version of the letter "t" started to be seen by her. Then, the cops redirected her to a place called "heaven".', 'user_reports': [], 'saved': False, 'mod_reason_title': None, 'gilded': 0, 'clicked': False, 'title': 'wtf;', 'link_flair_richtext': [], 'subreddit_name_prefixed': 'r/copypasta', 'hidden': False, 'pwls': 0, 'link_flair_css_class': '', 'downs': 0, 'thumbnail_height': None, 'top_awarded_type': None, 'parent_whitelist_status': 'no_ads', 'hide_score': False, 'name': 't3_z3v45w', 'quarantine': False, 'link_flair_text_color': 'dark', 'upvote_ratio': 1.0, 'author_flair_background_color': None, 'subreddit_type': 'public', 'ups': 1, 'total_awards_received': 0, 'media_embed': {}, 'thumbnail_width': None, 'author_flair_template_id': None, 'is_original_content': False, 'author_fullname': 't2_agnr6s5r', 'secure_media': None, 'is_reddit_media_domain': False, 'is_meta': False, 'category': None, 'secure_media_embed': {}, 'link_flair_text': 'Trigger Warning', 'can_mod_post': False, 'score': 1, 'approved_by': None, 'is_created_from_ads_ui': False, 'author_premium': False, 'thumbnail': 'spoiler', 
'edited': False, 'author_flair_css_class': None, 'author_flair_richtext': [], 'gildings': {}, 'content_categories': None, 'is_self': True, 'mod_note': None, 'created': 1669325318.0, 'link_flair_type': 'text', 'wls': 0, 'removed_by_category': None, 'banned_by': None, 'author_flair_type': 'text', 'domain': 'self.copypasta', 'allow_live_comments': False, 'selftext_html': '&lt;!-- SC_OFF --&gt;&lt;div class="md"&gt;&lt;p&gt;A girlfriend of mine was having a good day in the house. but suddenly; she got shrunk. she tried to move but she fell. also, she started to see tiny dots on the floor that she could walk on. when she walked on the dots, she couldn&amp;#39;t move again. She called 911 and 12 invisible cops arrived to her. and they were 
fluent at Assyrian. and the cops started to pick her up. A paper version of the letter &amp;quot;t&amp;quot; started to be seen by her. Then, the cops redirected her to a place called &amp;quot;heaven&amp;quot;.&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;', 'likes': None, 'suggested_sort': None, 'banned_at_utc': None, 'view_count': None, 'archived': False, 'no_follow': 
True, 'is_crosspostable': False, 'pinned': False, 'over_18': False, 'all_awardings': [], 'awarders': [], 'media_only': False, 'link_flair_template_id': '32ca29c8-a817-11e6-bbe7-0e41e4221050', 'can_gild': False, 'spoiler': True, 'locked': False, 'author_flair_text': None, 'treatment_tags': [], 'visited': False, 'removed_by': None, 'num_reports': None, 'distinguished': None, 'subreddit_id': 't5_2r6z7', 'author_is_blocked': False, 'mod_reason_by': None, 'removal_reason': None, 'link_flair_background_color': '#d3d6da', 'id': 'z3v45w', 'is_robot_indexable': True, 'num_duplicates': 0, 'report_reasons': None, 'author': 'drftggghkj', 'discussion_type': None, 'num_comments': 1, 'send_replies': True, 'media': None, 'contest_mode': False, 'author_patreon_flair': False, 'author_flair_text_color': None, 'permalink': '/r/copypasta/comments/z3v45w/wtf/', 'whitelist_status': 'no_ads', 'stickied': False, 'url': 'https: //www.reddit.com/r/copypasta/comments/z3v45w/wtf/', 'subreddit_subscribers': 1028883, 'created_utc': 1669325318.0, 'num_crossposts': 0, 'mod_reports': [], 'is_video': False}}], 'before': None}}, {'kind': 'Listing', 'data': {'after': None, 'dist': None, 'modhash': '', 'geo_filter': '', 'children': [{'kind': 't1', 'data': {'subreddit_id': 't5_2r6z7', 'approved_at_utc': None, 'author_is_blocked': False, 'comment_type': None, 'awarders': [], 'mod_reason_by': None, 'banned_by': None, 'author_flair_type': 'text', 'total_awards_received': 0, 'subreddit': 'copypasta', 'author_flair_template_id': None, 'likes': None, 'replies': '', 'user_reports': [], 'saved': False, 'id': 'ixnre83', 'banned_at_utc': None, 'mod_reason_title': None, 'gilded': 0, 'archived': False, 'collapsed_reason_code': None, 'no_follow': True, 'author': 'shittytranslatorbot3', 'can_mod_post': False, 'created_utc': 1669325352.0, 'send_replies': True, 'parent_id': 't3_z3v45w', 'score': 1, 'author_fullname': 't2_u2945ozs', 'approved_by': None, 'mod_note': None, 'all_awardings': [], 'collapsed': False, 'body': 'My boyfriend is a good day at home. But suddenly; He tried to move but fell. He also started to see the small areas where he could visit. When he left his point of view, he couldn\'t move. He called the 911 police and did not see 12 
people and spoke well. And the police started to see the "T" type. The police organized it somewhere as a "cloud".\n\n---\n***This is a bot, and this action was performed automatically. 
If you think the content of this message is inappropriate (e.g., goes against Reddit\'s content policy or does not belong here), please reply to this message with `!remove`.***', 'edited': False, 'top_awarded_type': None, 'author_flair_css_class': None, 'name': 't1_ixnre83', 'is_submitter': False, 'downs': 0, 'author_flair_richtext': [], 'author_patreon_flair': False, 'body_html': '&lt;div class="md"&gt;&lt;p&gt;My boyfriend is a good day at home. But suddenly; He tried to move but fell. He also started to see the small areas where he could visit. When he left his point of view, he couldn&amp;#39;t move. He called the 911 police and did not see 12 people and spoke well. And the police started to see the &amp;quot;T&amp;quot; type. The police organized it somewhere as a &amp;quot;cloud&amp;quot;.&lt;/p&gt;\n\n&lt;hr/&gt;\n\n&lt;p&gt;&lt;strong&gt;&lt;em&gt;This is a bot, and this action was performed automatically. If you think the content of this message is inappropriate (e.g., goes against Reddit&amp;#39;s content policy or does not belong here), please reply to this message with &lt;code&gt;!remove&lt;/code&gt;.&lt;/em&gt;&lt;/strong&gt;&lt;/p&gt;\n&lt;/div&gt;', 'removal_reason': None, 'collapsed_reason': None, 'distinguished': None, 'associated_award': None, 'stickied': False, 
'author_premium': False, 'can_gild': True, 'gildings': {}, 'unrepliable_reason': None, 'author_flair_text_color': None, 'score_hidden': False, 'permalink': '/r/copypasta/comments/z3v45w/wtf/ixnre83/', 'subreddit_type': 'public', 'locked': False, 'report_reasons': None, 'created': 1669325352.0, 'author_flair_text': None, 'treatment_tags': [], 'link_id': 't3_z3v45w', 'subreddit_name_prefixed': 'r/copypasta', 'controversiality': 0, 'depth': 0, 'author_flair_background_color': None, 'collapsed_because_crowd_control': None, 'mod_reports': [], 'num_reports': None, 'ups': 1
                    }
                }
            ], 'before': None
        }
    }
]